param:
  server-port: 8080
  db-ip: localhost
  db-port: 3306
  db-name: demo
  db-username: root
  db-password: password
  ignored-static-paths:

server:
  port: ${param.server-port}
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
  tomcat:
    basedir: ./tomcat/
    accesslog:
      directory: logs
      pattern:  '%h %l %u %t %D "%r" %s %b'
      enabled: true

mybatis:
  config-locations: classpath:mybatis/mybatis-config.xml

logging:
  path: ./logs/
  level:
    com.netflix: TRACE

zuul:
  ignored-patterns: ${param.ignored-static-paths}
  routes:
#    app-login:
#      path: /
#      url: http://localhost:8080/platform/console/main
    app-platform:
      path: /platform/**
      url: http://localhost:8080/platform/
    app-platform-static:
      path: /static/platform/**
      url: http://localhost:8080/static/platform/
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000

spring:
  thymeleaf:
    cache: false
    model: LEGACYHTML5
    prefix=classpath: /templates/thymeleaf/
  datasource:
    gateway:
      validation-query: SELECT 1 FROM DUAL
      test-on-borrow: true
      test-while-idle: true
      time-between-eviction-runs-millis: 3600000
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://${param.db-ip}:${param.db-port}/${param.db-name}?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=round
      username: ${param.db-username}
      password: ${param.db-password}
  http:
    multipart:
      maxFileSize: 100Mb
      maxRequestSize: 100Mb
  session:
    store-type: jdbc
  jdbc:
    initializer:
      enabled: true
  profiles:
    active: ${RUN_ENV}
