param:
  server-port: 8082
  db-ip: 192.168.1.13
  db-port: 3306
  db-name: webgateway_demo
  db-username: root
  db-password:
  ignored-static-paths:

zuul:
    routes:
      app-platform:
        path: /platform/**
  #      url: http://${param.platform-server}/platform/
        serviceId: platform
        stripPrefix: false
      app-platform-static:
        path: /static/platform/**
        url: http://${param.platform-server}/static/platform/

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.46:1111/eureka/
spring:
  application:
    name: gateway